use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMDownloadCenterServices_Example' do
  pod 'AHFMDownloadCenterServices', :path => '../'

  target 'AHFMDownloadCenterServices_Tests' do
    inherit! :search_paths

    
  end
end
